export const GET_TRANSACTION_HISTORY = 'GET_TRANSACTION_HISTORY';
export const DEPOSITE_AMOUNT_WALLET = 'DEPOSITE_AMOUNT_WALLET';
export const WITHDRAW_AMOUNT_WALLET = 'WITHDRAW_AMOUNT_WALLET';
export const GET_ALL_BALANCE = 'GET_ALL_BALANCE';
